#!/usr/bin/env python3
"""Generate src/fuji_tags.rs from ExifTool's FujiFilm.pm.

Transcribing lookup tables by hand is how you get a film simulation that reads
"Velvia" when the camera said "Provia", so the tables are extracted rather than
typed. Run it against a checkout of ExifTool and commit the result:

    python3 tools/extract-fuji.py /path/to/exiftool/lib/Image/ExifTool/FujiFilm.pm

Only the tags in WANT are emitted. The goal is the film recipe and the fields a
photographer reads, not all 200 tags in the table.

Two tags are deliberately absent. InternalSerialNumber needs a ValueConv that
decodes a date out of embedded hex, and it publishes a camera serial number,
which is not a thing this should print by default. FlickerReduction prints in
hex through an expression. Neither is worth rendering differently from
ExifTool, and absent beats wrong.
"""
import re, subprocess, sys, pathlib

WANT = {
 0x1000:"Quality", 0x1001:"Sharpness", 0x1002:"WhiteBalance", 0x1003:"Saturation",
 0x1004:"Contrast", 0x100a:"FocusPixel", 0x100b:"NoiseReduction", 0x100e:"NoiseReduction",
 0x100f:"Clarity", 0x1010:"FujiFlashMode", 0x1011:"FlashExposureComp",
 0x1020:"Macro", 0x1021:"FocusMode", 0x1023:"FocusPixel2", 0x1030:"SlowSync",
 0x1031:"PictureMode", 0x1040:"ShadowTone", 0x1041:"HighlightTone",
 0x1044:"DigitalZoom", 0x1045:"LensModulationOptimizer",
 0x1047:"GrainEffectRoughness", 0x1048:"ColorChromeEffect",
 0x104c:"GrainEffectSize", 0x104d:"CropMode", 0x104e:"ColorChromeFXBlue",
 0x1050:"ShutterType", 0x1100:"AutoBracketing", 0x1101:"SequenceNumber",
 0x1153:"ImageStabilization", 0x1400:"DynamicRange", 0x1401:"FilmMode",
 0x1402:"DynamicRangeSetting", 0x1403:"DevelopmentDynamicRange",
 0x1404:"MinFocalLength", 0x1405:"MaxFocalLength",
 0x1406:"MaxApertureAtMinFocal", 0x1407:"MaxApertureAtMaxFocal",
 0x140b:"AutoDynamicRange", 0x1443:"DRangePriority", 0x1444:"DRangePriorityAuto",
 0x1445:"DRangePriorityFixed", 0x1002_0:"", 0x100c:"WhiteBalanceFineTune",
 0x1005:"ColorTemperature", 0x1006:"WhiteBalanceFineTune2",
}

src = pathlib.Path(sys.argv[1]).read_text(errors="replace")
# The Main table runs from its declaration to the next top-level %Image::ExifTool
start = src.index("%Image::ExifTool::FujiFilm::Main = (")
end = src.index("%Image::ExifTool::FujiFilm::", start + 10)
body = src[start:end]

# Each entry: 0xNNNN => { ... }  or  0xNNNN => { Name => '...' },
entries = {}
for m in re.finditer(r"\n    (0x[0-9a-fA-F]+) => \{", body):
    tid = int(m.group(1), 16)
    if tid not in WANT:
        continue
    # brace-match forward from the opening brace
    i = m.end() - 1
    depth, j = 0, i
    while j < len(body):
        if body[j] == "{": depth += 1
        elif body[j] == "}":
            depth -= 1
            if depth == 0: break
        j += 1
    blob = body[i:j+1]
    name = re.search(r"Name\s*=>\s*'([^']+)'", blob)
    name = name.group(1) if name else WANT[tid]
    pc = {}
    pcm = re.search(r"PrintConv\s*=>\s*\{", blob)
    if pcm:
        k = pcm.end() - 1
        depth, l = 0, k
        while l < len(blob):
            if blob[l] == "{": depth += 1
            elif blob[l] == "}":
                depth -= 1
                if depth == 0: break
            l += 1
        for km in re.finditer(r"(0x[0-9a-fA-F]+|-?\d+)\s*=>\s*'((?:[^'\\]|\\.)*)'", blob[k:l]):
            key = int(km.group(1), 0)
            pc[key] = km.group(2).replace("\\'", "'").replace("\\\\", "\\")
    entries[tid] = (name, pc)

out = ["//! Fujifilm MakerNotes tags.",
       "//!",
       "//! GENERATED by tools/extract-fuji.py from ExifTool's FujiFilm.pm. Do not",
       "//! edit by hand: the point of generating it is that a mistyped film",
       "//! simulation is invisible until somebody reads the wrong recipe off a",
       "//! photo. Re-run the script to pick up a new camera's values.",
       "//!",
       "//! Tag meanings are ExifTool's, 25 years of them. See NOTICE.",
       "",
       "use crate::tags::{Conv, TagDef};",
       "",
       f"pub static FUJI: &[TagDef] = &[",]
for tid in sorted(entries):
    name, pc = entries[tid]
    if pc:
        pairs = ", ".join(f'({k}, "{v}")' for k, v in sorted(pc.items()))
        out.append(f'    TagDef {{ id: {tid:#06x}, name: "{name}", conv: Conv::Map(&[{pairs}]) }},')
    else:
        out.append(f'    TagDef {{ id: {tid:#06x}, name: "{name}", conv: Conv::None }},')
out.append("];")
out_path = pathlib.Path("src/fuji_tags.rs")
out_path.write_text("\n".join(out) + "\n")
# Format it here rather than leaving a file that fails `cargo fmt --check`,
# which would make every regeneration look like a change to the whole table.
subprocess.run(["rustfmt", "--edition", "2021", str(out_path)], check=False)
print(f"wrote {out_path} with {len(entries)} tags")
